# need to figure out how to get from netmaker-devops repo to get the dockerfile and modhtml.sh script to build it.
name: create docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true