# need to figure out how to get from netmaker-devops repo to get the dockerfile and modhtml.sh script to build it.
name: create docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:

  build-docs:
    runs-on: ubuntu-latest
    

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gravitl/netmaker-docs
          ref: master
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup=buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            gravitl/netmaker-docs:${{ inputs.version }}
            gravitl/netmaker-docs:latest
