# need to figure out how to get from netmaker-devops repo to get the dockerfile and modhtml.sh script to build it.
name: create docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        run: |
          git config --global user.name "Gravitl"
          git config --global user.email "info@netmaker.io"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gravitl/netmaker-docs
          ref: master
      - name: Build Docs
        env:
          TOKEN: ${{ secrets.repo_token }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/gravitl/netmaker-devops/master/netmaker-docs/Dockerfile
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/gravitl/netmaker-devops/master/netmaker-docs/mod-html.sh
          mv Dockerfile netmaker-docs
          mv mod-html.sh netmaker-docs
          cd netmaker-docs
          make html
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup=buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            gravitl/netmaker-docs:${{ inputs.version }}
            gravitl/netmaker-docs:latest
      - name: Update Server
        run: |
          ssh root@143.198.165.134 "bash updateimage.sh ${{ inputs.version }}"
