# creates a release from master
# builds docs, pushes to docker hub and updates docs server

name: Docs_deploy

on:
  push:
    branches:
      - main

jobs:

  release:
    uses: gravitl/devops/.github/workflows/deploydocs.yml@master
    secrets: inherit