# creates a release from master
# builds docs, pushes to docker hub and updates docs server

name: Docs_deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:

  release:
    uses: gravitl/netmaker-devops/.github/workflows/deploydocs.yml@master
    env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      version: ${{ inputs.version }}
    secrets: inherit