name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
    - name: Generate Name:
      id: name
      run: |
        echo "ARTIFACT_NAME=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HTMLupload${{ steps.name.outputs.ARTIFACT_NAME }}
        path: ./_build/html/