# copied from https://rtds-action.readthedocs.io/en/latest/ 
# need to get webhook token from readthedocs.
# You should also edit your webhook settings on GitHub by going to https://github.com/USERNAME/REPONAME/settings/hooks and clicking “Edit” next to the ReadTheDocs hook. On that page, you should un-check the Pushes option.
name: Docs
on: workflow_dispatch

jobs:
  deploy_readthedocs:
    name: "Build the docs for readthedocs.org"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}